-- COMANDO PARA CREAR BASE DE DATOS
CREATE DATABASE LABUHARDILLA;
USE LABUHARDILLA;

-- CREO TABLA COLORES
CREATE TABLE COLOR
(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(15) NOT NULL
);

-- CREO TABLA CATEGORIAS
CREATE TABLE CATEGORY
(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL
);

-- CREO TABLA PORODUCTOS
CREATE TABLE PRODUCTS
(
	id INT UNSIGNED AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    price DOUBLE NOT NULL,
    id_category INT UNSIGNED NOT NULL,
    id_color INT UNSIGNED NOT NULL,
    image VARCHAR(50) NULL,
    description VARCHAR(500) NULL,
    stock INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_category) REFERENCES CATEGORY(id),
    FOREIGN KEY (id_color) REFERENCES COLOR(id)
);

-- CREO TABLA ROLES
CREATE TABLE ROLE
(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(15) NOT NULL
);

-- CREO TABLA PROVINCIAS
CREATE TABLE PROVINCES
(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(25) NOT NULL
);

-- CREO TABLA LOCALIDADES
CREATE TABLE CITIES
(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    id_province INT UNSIGNED NOT NULL,
    name VARCHAR(30) NOT NULL,
    zip_code INT UNSIGNED NULL,
    FOREIGN KEY (id_province) REFERENCES PROVINCES(id)
);

-- CREO TABLA USUARIOS
CREATE TABLE USERS
(
	id INT UNSIGNED AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(150) NOT NULL,
    image VARCHAR(50) NULL,
    id_role INT UNSIGNED NOT NULL,
    phone VARCHAR(20) NULL,
    address VARCHAR(40) NULL,
    id_city INT UNSIGNED NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_role) REFERENCES ROLE(id),
    FOREIGN KEY (id_city) REFERENCES CITIES(id)
);

-- CREO TABLA FORMAS DE PAGO
CREATE TABLE PAYMENTS
(
	id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(15) NOT NULL
);

-- CREO TABLA CARRITO
CREATE TABLE CART
(
	id INT UNSIGNED AUTO_INCREMENT,
    purchase_date DATE NOT NULL,
    id_user INT UNSIGNED NOT NULL,
    id_payment INT UNSIGNED NOT NULL,
    total DOUBLE NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_user) REFERENCES USERS(id),
    FOREIGN KEY (id_payment) REFERENCES PAYMENTS(id)
);

-- CREO TABLA PRODUCTOS POR VENTA
CREATE TABLE ITEMS_CART
(
	id INT UNSIGNED AUTO_INCREMENT,
    id_cart INT UNSIGNED NOT NULL,
    id_product INT UNSIGNED NOT NULL,
    quantity INT UNSIGNED NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (id_cart) REFERENCES CART(id),
    FOREIGN KEY (id_product) REFERENCES PRODUCTS(id)
);